keys:
  guild_ids: []
  discordtoken: ""
  openaikey: ""
voice:
  enabled: true
  vcfilepath: ""
  vcconfigpath: ""
text:
  enabled: true
  savechatlogs: true
  chatlogfolder: "" #leave empty if you want it to not save to a fodler
genparams:
  temp: 0.9
  max_tokens: 125
  presence_penalty: 0.1
  backforths: 5
